# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: edd665b02ecb963f32116569ef77758d639db3285cec29c553adbda7af5316a8af4710492101b472af9c14d046054b3ffd75d05121e5cfcfe9ad22faf3c931f3

test:
  secret_key_base: 44db50588495f31f30709e06d63c77f9e781810001ff50c7f1b0c778000f86f63266a0cd19d3db75b815d157dcb9aba5b8e6ff0ddeee1f1de4cc7b90485cad87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
